version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: avatar_teleporter
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  state:
    image: asia.gcr.io/at-sdk/at-state-server:1.0-rc1
    links:
      - redis
    environment:
      STATE_SERVER_INSECURE: "true"
  core:
    image: asia.gcr.io/at-sdk/at-core-server:1.0-rc1
    command: ["-c", "config.toml", "-migrate"]
    links:
      - mysql
      - state
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./credentials:/app/credentials
    environment:
      CORE_SERVER_INSECURE: "true"
      MYSQL_PASSWORD: p@ssword
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
  atp:
    image: asia.gcr.io/at-sdk/at-atp-server:1.0-rc1
    links:
      - state
    ports:
      - "10000:10000/udp"
    environment:
      ATP_SERVER_INSECURE: "true"
