//
// Setting は設定に関する情報を操作します。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.8
// source: core/setting.proto

package core

import (
	common "github.com/SpiralMindJP/at-sdk/go/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// チーム設定取得リクエストを表します。
type GetTeamSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId int64 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // チームID。
}

func (x *GetTeamSettingRequest) Reset() {
	*x = GetTeamSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamSettingRequest) ProtoMessage() {}

func (x *GetTeamSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamSettingRequest.ProtoReflect.Descriptor instead.
func (*GetTeamSettingRequest) Descriptor() ([]byte, []int) {
	return file_core_setting_proto_rawDescGZIP(), []int{0}
}

func (x *GetTeamSettingRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

//
// チーム設定取得レスポンスを表します。
type GetTeamSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setting *common.TeamSetting `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"` // チーム設定。
}

func (x *GetTeamSettingResponse) Reset() {
	*x = GetTeamSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamSettingResponse) ProtoMessage() {}

func (x *GetTeamSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamSettingResponse.ProtoReflect.Descriptor instead.
func (*GetTeamSettingResponse) Descriptor() ([]byte, []int) {
	return file_core_setting_proto_rawDescGZIP(), []int{1}
}

func (x *GetTeamSettingResponse) GetSetting() *common.TeamSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

//
// チーム設定の設定リクエストを表します。
type SetTeamSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Setting *common.TeamSetting `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"` // チーム設定。
}

func (x *SetTeamSettingRequest) Reset() {
	*x = SetTeamSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_setting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTeamSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTeamSettingRequest) ProtoMessage() {}

func (x *SetTeamSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_setting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTeamSettingRequest.ProtoReflect.Descriptor instead.
func (*SetTeamSettingRequest) Descriptor() ([]byte, []int) {
	return file_core_setting_proto_rawDescGZIP(), []int{2}
}

func (x *SetTeamSettingRequest) GetSetting() *common.TeamSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

//
// チーム設定削除リクエストを表します。
type DeleteTeamSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId int64 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // チームID。
}

func (x *DeleteTeamSettingRequest) Reset() {
	*x = DeleteTeamSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_setting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTeamSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamSettingRequest) ProtoMessage() {}

func (x *DeleteTeamSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_setting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamSettingRequest) Descriptor() ([]byte, []int) {
	return file_core_setting_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTeamSettingRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

var File_core_setting_proto protoreflect.FileDescriptor

var file_core_setting_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61,
	0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x49, 0x0a,
	0x15, 0x53, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x33, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x32, 0xfd, 0x01,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4e, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x21, 0x2e, 0x61, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x70, 0x69, 0x72,
	0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x64, 0x4a, 0x50, 0x2f, 0x61, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_core_setting_proto_rawDescOnce sync.Once
	file_core_setting_proto_rawDescData = file_core_setting_proto_rawDesc
)

func file_core_setting_proto_rawDescGZIP() []byte {
	file_core_setting_proto_rawDescOnce.Do(func() {
		file_core_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_setting_proto_rawDescData)
	})
	return file_core_setting_proto_rawDescData
}

var file_core_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_setting_proto_goTypes = []interface{}{
	(*GetTeamSettingRequest)(nil),    // 0: at.core.GetTeamSettingRequest
	(*GetTeamSettingResponse)(nil),   // 1: at.core.GetTeamSettingResponse
	(*SetTeamSettingRequest)(nil),    // 2: at.core.SetTeamSettingRequest
	(*DeleteTeamSettingRequest)(nil), // 3: at.core.DeleteTeamSettingRequest
	(*common.TeamSetting)(nil),       // 4: at.common.TeamSetting
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_core_setting_proto_depIdxs = []int32{
	4, // 0: at.core.GetTeamSettingResponse.setting:type_name -> at.common.TeamSetting
	4, // 1: at.core.SetTeamSettingRequest.setting:type_name -> at.common.TeamSetting
	0, // 2: at.core.SettingService.GetTeamSetting:input_type -> at.core.GetTeamSettingRequest
	2, // 3: at.core.SettingService.SetTeamSetting:input_type -> at.core.SetTeamSettingRequest
	3, // 4: at.core.SettingService.DeleteTeamSetting:input_type -> at.core.DeleteTeamSettingRequest
	1, // 5: at.core.SettingService.GetTeamSetting:output_type -> at.core.GetTeamSettingResponse
	5, // 6: at.core.SettingService.SetTeamSetting:output_type -> google.protobuf.Empty
	5, // 7: at.core.SettingService.DeleteTeamSetting:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_setting_proto_init() }
func file_core_setting_proto_init() {
	if File_core_setting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_setting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTeamSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_setting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTeamSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_setting_proto_goTypes,
		DependencyIndexes: file_core_setting_proto_depIdxs,
		MessageInfos:      file_core_setting_proto_msgTypes,
	}.Build()
	File_core_setting_proto = out.File
	file_core_setting_proto_rawDesc = nil
	file_core_setting_proto_goTypes = nil
	file_core_setting_proto_depIdxs = nil
}
