= AT Customer Client をネイティブアプリに埋め込む手順
:author:    株式会社SpiralMind
:revnumber: 2.0
:revdate:   2021-05-24

== Android Studio でプロジェクトを作成する

1. 任意のテンプレートを選択し、*Next* をクリック。
2. プロジェクトの情報を入力する。
3. *Minimum SDK* は、*API 19: Android 4.4 (KitKat)* 以上を選択する。
4. *Finish* をクリックし、プロジェクトを作成する。

=== Android Studio で AAR をインポートしてモジュールを生成

1. *File > New > New Module...* でモジュール生成画面を開く。
2. *Import .JAR/.AAR Package* を選択して *Next* をクリック。
3. *File name* で AAR のパスを指定する。
4. サブプロジェクト名に、`at-customer-client` を設定する。
5. *Finish* をクリックし、モジュールを生成する。

=== 依存関係の追加

1. build.gradle (:app) を開く
2. `dependencies` に以下を追加
+
[source, gradle]
----
dependencies {
    implementation project(':at-customer-client')

    ...
}
----
3. *File > Sync Project with Gradle Files* を実行し、プロジェクトを同期させる。

=== Unity 内部で仕様している文字列リソースを追加

`strings.xml` に、`game_view_content_description` という名前で `Game view` という文字列を追加する。

[source, xml]
----
<resources>
    <string name="app_name">AT Customer</string>
    <string name="game_view_content_description">Game view</string>
</resources>
----

=== Unity を表示する Activity を作成

`jp.spiralmind.avatar_teleporter.customer.ATCustomerClientActivity` をインポートし、`ATCustomerClientActivity` を継承したクラスを定義する。

[source, java]
----
import jp.spiralmind.avatar_teleporter.customer.ATCustomerClientActivity;

public class ATCustomerActivity extends ATCustomerClientActivity {
}
----

必要に応じ、`onCreate` や `onNewIntent` をオーバーライドする。

Unity の画面に Android のネイティブコントロールを配置する場合は、`onCreate` イベントにて追加する。
`mUnityPlayer` メンバーは `FrameLayout` なので、`addView` メソッドを呼び出して各種ビューを追加できる。

v2.0 以降は、`ATCustomerClientActivity` は抽象クラスとなっています。
抽象メソッド、`onAvatarSceneStateChanged` をオーバーライドしてください。

=== Unity を表示する Activity を起動する

Unity を表示する Activity を指定した `Intent` を作成し、画面を起動する。

[source, java]
----
Intent intent = new Intent(this, ATCustomerActivity.class);
intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);
startActivityForResult(intent, 1);
----

=== ATCustomerClientActivity で利用可能なメソッド

==== SetViewport メソッド

ビューポートを設定します。
画面は、左下を原点とした 0 から 1.0 の数値で表されます。

[source, java]
----
public void SetViewport(float x, float y, float w, float h)
----

.パラメーター
x:: Viewport の x 座標。
y:: Viewport の y 座標。
w:: Viewport の幅。
h:: Viewport の高さ。

==== ShowSettingView メソッド

設定画面を表示します。

[source, java]
----
public void ShowSettingView()
----

==== ShowSelectServerView メソッド

サーバー選択画面を表示します。

[source, java]
----
public void ShowSelectServerView()
----

==== onAvatarSceneStateChanged メソッド (v2.0 以降)

このメソッドは、抽象メソッドです。

メソッドをオーバーライドすることで、アバターシーンの状態変更を受け取ることができます。

[source, java]
----
    @Override
    protected void onAvatarSceneStateChanged(String state)
    {
    }
----

各状態は以下のようになります。


.イベント状態値
|===
| 状態値 | 説明

| `"started"`
| アバターシーンが開始された。

| `"connecting"`
| 接続中。

| `"reconnecting"`
| 再接続中

| `"online"`
| オンライン。

| `"offline"`
| オフライン。

| `"operator-joined"`
| オペレーターが入室した。

| `"operator-leaved"`
| オペレーターが退室した。

| `"exit"`
| アバターシーンが終了した。

|===

== Tips

* フルスクリーンレンダリングのみサポート。スクリーンの一部へのレンダリングはサポートしない。
* 2つ以上の Unity ランタイムのロードはサポートしない。
* Unity は x86 をサポートしなくなった。よって、x86 で動作する Android エミュレーターでは動作しない。

== 動作要件

OS:: Android 4.4 (API 19) 以上
CPU:: ARMv7 with Neon Support (32-bit) または ARM64
グラフィックAPI:: OpenGL ES 2.0+, OpenGL ES 3.0+, Vulkan
その他::
* 1GB 以上の RAM
* サポートされているハードウェアデバイスは、Google による Android の互換性定義（link:https://source.android.com/compatibility/9/android-9-cdd[Version 9.0 ]）を満たしているか、それ以上である必要があります。
    1. Handheld (Section 2.2)
    2. Television (Section 2.3)
    3. Tablets (Section 2.6)
* ハードウェアは、Android OS がネイティブで動作している必要があります。コンテナやエミューレーター内の Android には対応していません。
